# Generated by Django 3.2.4 on 2021-07-07 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('idMecanico', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de Mecanico')),
                ('nombreMecanico', models.CharField(max_length=60, verbose_name='nombre del mecanico')),
                ('especialidad', models.CharField(max_length=30, verbose_name='especialidad del mecanico')),
                ('fotoPerfil', models.CharField(max_length=100, verbose_name='foto del mecanico')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de usuario')),
                ('email', models.CharField(max_length=50, verbose_name='email del usuario')),
                ('contraseña', models.CharField(max_length=12, verbose_name='contraseña del usuario')),
                ('tipoUsuario', models.CharField(max_length=15, verbose_name='tipo de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('idTrabajo', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de Trabajo')),
                ('nombreTrabajo', models.CharField(max_length=30, verbose_name='nombre de trabajo')),
                ('foto', models.CharField(max_length=100, verbose_name='fotografia del trabajo')),
                ('descripcion', models.CharField(max_length=250, verbose_name='descripcion del trabajo')),
                ('categoria', models.CharField(max_length=30, verbose_name='categoria del trabajo')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mecanico')),
            ],
        ),
        migrations.AddField(
            model_name='mecanico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
    ]
