# Generated by Django 3.2.4 on 2021-07-08 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210707_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanico',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
    ]
