# Generated by Django 3.2.4 on 2021-07-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mecanico_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('modelo_vehiculo', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=60)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='especialidad',
            field=models.CharField(max_length=50, verbose_name='Especialidad del mecanico'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='categoria',
            field=models.CharField(max_length=50, verbose_name='Categoria del trabajo'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
